[bell]
animation = "EaseOutExpo"
duration = 0

# TokyoNight Alacritty Colors Light
# Default colors
[colors.primary]
background = '#e1e2e7'
foreground = '#3760bf'

[colors.cursor]
cursor = '#3760bf'
text = '#e1e2e7'

# Normal colors
[colors.normal]
black = '#e9e9ed'
red = '#f52a65'
green = '#587539'
yellow = '#8c6c3e'
blue = '#2e7de9'
magenta = '#9854f1'
cyan = '#007197'
white = '#6172b0'

# Bright colors
[colors.bright]
black = '#a1a6c5'
red = '#f52a65'
green = '#587539'
yellow = '#8c6c3e'
blue = '#2e7de9'
magenta = '#9854f1'
cyan = '#007197'
white = '#3760bf'

# Indexed Colors
[[colors.indexed_colors]]
index = 16
color = '#b15c00'

[[colors.indexed_colors]]
index = 17
color = '#c64343'


# TokyoNight Alacritty Colors Dark
# Default colors
# [colors.primary]
# background = '#1a1b26'
# foreground = '#c0caf5'
#
# [colors.cursor]
# cursor = '#c0caf5'
# text = '#1a1b26'
#
# # Normal colors
# [colors.normal]
# black = '#15161e'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#a9b1d6'
#
# # Bright colors
# [colors.bright]
# black = '#414868'
# red = '#f7768e'
# green = '#9ece6a'
# yellow = '#e0af68'
# blue = '#7aa2f7'
# magenta = '#bb9af7'
# cyan = '#7dcfff'
# white = '#c0caf5'
#
# # Indexed Colors
# [[colors.indexed_colors]]
# index = 16
# color = '#ff9e64'
#
# [[colors.indexed_colors]]
# index = 17
# color = '#db4b4b'


[cursor]
style = "Block"

[env]
LANG = "en_US.UTF-8"
LC_ALL = "en_US.UTF-8"
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[scrolling]
history = 10000

[shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
decorations = "full"
startup_mode = "Maximized"
title = "Alacritty"
option_as_alt = 'Both'

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0
